'use strict';
const assert=require('assert');
const CONFIG=require('../config');
const components=require('../menus/html/components');
assert.strictEqual(CONFIG.support.number,'5519981144235');
assert(!CONFIG.owner.numbers.includes('5519981144235'));
const html=components.botaoSuporte();
assert(html.includes('class="support-button"'));
assert(html.includes('href="https://wa.me/5519981144235"'));
assert(html.includes('target="_blank"'));
assert(html.includes('SUPORTE'));
const footer=components.rodape({prefix:'!',avisoCorte:null});
assert(footer.includes('support-button'));
assert(footer.includes('https://wa.me/5519981144235'));
assert(!footer.includes('text='));
console.log('supportButton.test.js: OK');
const templates=require('../menus/html/templates');
const documentHtml=templates.menuPrincipal({botName:'Lua',version:'1',emoji:'',prefix:'!',total:0,categoriaLabel:'Menu',escopoTexto:'no privado',grupo:{categorias:[],inicial:'',titulo:'Menu',total:0},altura:640,passo:.7,ident:{prefixo:'!'},visual:null});
assert(documentHtml.includes('support-button'));
assert(documentHtml.includes('https://wa.me/5519981144235'));
console.log('supportButton HTML flow: OK');
