'use strict';
const audit=require('../database/communityAudit'); const resolver=require('./communityResolver');
const group=(j)=>String(j||'').endsWith('@g.us');
async function meta(ctx,j){try{return await ctx.socket.groupMetadata(j);}catch(_){return null;}}
async function execute(ctx){const sub=String(ctx.args&&ctx.args[0]||'status').toLowerCase(); if(['avisos','set'].includes(sub)){if(!ctx.isOwner)return ctx.reply('🚫 Apenas o dono pode configurar a auditoria.'); if(!group(ctx.remoteJid))return ctx.reply('⚠️ Use este comando dentro do grupo de Avisos.'); const m=await meta(ctx,ctx.remoteJid); const c=m&&group(m.linkedParent)?m.linkedParent:null; if(!c)return ctx.reply('⚠️ Não consegui identificar a comunidade deste grupo com segurança. Use: ,database vincular <communityJid> <announcementJid>'); audit.configureCommunity({communityJid:c,announcementJid:ctx.remoteJid,resolutionMode:'automatic',communityName:m.subject||''}); return ctx.reply('✅ Avisos da comunidade configurados automaticamente.');}
if(['vincular','link'].includes(sub)){if(!ctx.isOwner)return ctx.reply('🚫 Apenas o dono pode configurar a auditoria.'); const c=ctx.args[1], a=ctx.args[2], g=ctx.remoteJid; if(!group(c)||!group(a)||!group(g))return ctx.reply('❌ Use dentro do grupo filho: ,database vincular <communityJid> <announcementJid>'); audit.linkGroup({communityJid:c,announcementJid:a,groupJid:g,resolutionMode:'manual'}); return ctx.reply('✅ Grupo vinculado à comunidade e aos Avisos informados.');}
if(sub==='off'){if(!ctx.isOwner)return ctx.reply('🚫 Apenas o dono pode desativar a auditoria.'); const r=await resolver.resolve(ctx.socket,ctx.remoteJid); if(r.status!=='RESOLVED')return ctx.reply('⚠️ Comunidade não resolvida; nada foi desativado.'); audit.setEnabled(r.communityJid,false); return ctx.reply('✅ Auditoria desativada. O histórico foi preservado.');}
if(sub==='on'){if(!ctx.isOwner)return ctx.reply('🚫 Apenas o dono pode ativar a auditoria.'); const r=await resolver.resolve(ctx.socket,ctx.remoteJid); if(r.status!=='RESOLVED')return ctx.reply('⚠️ Comunidade não resolvida.'); audit.configureCommunity({communityJid:r.communityJid,announcementJid:r.announcementJid,resolutionMode:r.mode}); return ctx.reply('✅ Auditoria ativada.');}
if(sub==='status'){const r=await resolver.resolve(ctx.socket,ctx.remoteJid); if(r.status!=='RESOLVED')return ctx.reply('🌙 *LUA • AUDITORIA*\nStatus: não resolvido\nComunidade: não identificada\nDestino: nenhum'); const c=audit.getCommunity(r.communityJid); const gs=audit.listGroups(r.communityJid); return ctx.reply(`🌙 *LUA • AUDITORIA*\n\nStatus: ${c&&c.enabled?'ATIVO':'INATIVO'}\nComunidade: ${c&&c.community_name||r.communityName}\nAvisos: ${r.announcementJid}\nResolução: ${(c&&c.resolution_mode||r.mode||'manual').toUpperCase()}\nGrupos vinculados: ${gs.length}\n\nEntrada: ON\nSaída: ON\nRemoção: ON\nPromoção: ON\nRebaixamento: ON`);}
return ctx.reply('🌙 *DATABASE*\n, database avisos\n, database vincular <communityJid> <announcementJid>\n, database status\n, database off');}
module.exports={execute};
