'use strict';
const crypto = require('crypto');
const renderer = require('../plugins/communityAudit/renderer');
const profile = require('../plugins/welcome/profile');
const resolver = require('./communityResolver');
const logger = require('./logger').child('community-audit');
const TYPES = { join:'JOIN', entrou:'JOIN', leave:'LEAVE', saiu:'LEAVE', remove:'REMOVE', removeu:'REMOVE', promote:'PROMOTE', promoveu:'PROMOTE', demote:'DEMOTE', rebaixou:'DEMOTE' };
const group = (jid) => String(jid || '').endsWith('@g.us');
function typeOf(value) { return TYPES[String(value || '').toLowerCase()] || null; }
function participantName(ctx) { const sender=String(ctx.sender||''); const found=(ctx.participants||[]).find(p=>[p.id,p.lid,p.phoneNumber].filter(Boolean).map(String).includes(sender)); return found&&(found.notify||found.name||found.pushName) || 'Karma'; }
function buildPreviewAuditEvent({ type, executor, groupMetadata, communityMetadata } = {}) { const now=new Date().toISOString(); const subject=groupMetadata&&groupMetadata.subject || ''; const community=communityMetadata&&communityMetadata.subject || 'Comunidade de Preview'; const name=executor&&executor.name || 'Karma'; return { eventId:`preview_${crypto.randomUUID()}`, type, groupJid:groupMetadata&&groupMetadata.id || null, participantJid:executor&&executor.jid || 'preview@lid', actorJid:executor&&executor.jid || 'preview@lid', participantDisplayName:name, participantName:name, actorDisplayName:type==='LEAVE'?'':(executor&&executor.name||'Karma'), groupName:subject || 'Grupo de Preview', communityName:community, memberCount:type==='JOIN'?(groupMetadata&&groupMetadata.participants||[]).length || 198:null, reason:type==='REMOVE'?'Teste de visualizacao':null, occurredAt:now, preview:true } }
function stressEvent(ctx) { const base=buildPreviewAuditEvent({type:'REMOVE',executor:{jid:ctx.sender||'preview@lid',name:'Karma - Participante com nome extremamente longo para testar o layout'},groupMetadata:{id:ctx.remoteJid,subject:'Lua Desenvolvimento com um nome muito longo para testar wrap e ellipsis',participants:ctx.participants||[]},communityMetadata:{subject:'Karma Community - Comunidade de testes visuais com nome extenso'}}); base.actorDisplayName='Nix - Responsavel administrativo com nome muito longo'; base.reason='Motivo de preview extremamente longo para verificar quebra de linha, limite de largura e recorte visual'; return base; }
async function renderAndSend(ctx, event, destination, avatarBuffer) { const image=await renderer.renderAuditCard(event,{avatarBuffer,preview:true}); logger.info({type:event.type,requestedBy:ctx.sender,sourceChat:ctx.remoteJid,destination:destination===ctx.remoteJid?'LOCAL':'ANNOUNCEMENT',rendered:true,sent:false},'[COMMUNITY_PREVIEW]'); await ctx.socket.sendMessage(destination,{image,caption:`LUA Community Audit - Preview: ${event.type}`}); logger.info({type:event.type,requestedBy:ctx.sender,sourceChat:ctx.remoteJid,destination:destination===ctx.remoteJid?'LOCAL':'ANNOUNCEMENT',rendered:true,sent:true},'[COMMUNITY_PREVIEW]'); }
async function execute(ctx, args) { if(!ctx.isOwner)return ctx.reply('🚫 Apenas o dono pode gerar previews.'); const requested=String(args&&args[0]||'').toLowerCase(); if(!requested)return ctx.reply('LUA - PREVIEW\n\n,database preview join\n,database preview leave\n,database preview remove\n,database preview promote\n,database preview demote\n,database preview all\n,database preview stress'); const toAnnouncements=String(args&&args[1]||'').toLowerCase()==='avisos'; let destination=ctx.remoteJid; let resolution=null; if(toAnnouncements){ resolution=await resolver.resolve(ctx.socket,ctx.remoteJid); if(resolution.status!=='RESOLVED'||!group(resolution.announcementJid))return ctx.reply('Não foi possível identificar os Avisos desta comunidade.\nUse o preview local ou configure o vínculo da comunidade.'); destination=resolution.announcementJid; }
 let events=[]; if(requested==='all')events=['JOIN','LEAVE','REMOVE','PROMOTE','DEMOTE']; else if(requested==='stress')events=['STRESS']; else {const t=typeOf(requested); if(!t)return ctx.reply('❌ Tipo de preview inválido. Use join, leave, remove, promote, demote, all ou stress.'); events=[t];}
 const executor={jid:ctx.sender,name:participantName(ctx)}; let groupMetadata={id:ctx.remoteJid,subject:ctx.groupName||'',participants:ctx.participants||[]}; let communityMetadata=null; if(resolution)communityMetadata={subject:resolution.communityName||'Comunidade de Preview'}; const avatar=await profile.getPhoto(ctx.socket,ctx.sender).catch(()=>null);
 for(const type of events){const event=type==='STRESS'?stressEvent(ctx):buildPreviewAuditEvent({type,executor,groupMetadata,communityMetadata}); event.preview=true; await renderAndSend(ctx,event,destination,avatar);}
 return true; }
module.exports={TYPES,typeOf,buildPreviewAuditEvent,execute,stressEvent};
