'use strict';
const $=s=>document.querySelector(s);let state=null,token=localStorage.getItem('luaImperiosSession'),selected=null,zoom=1;
async function exchangeTicket(){const ticket=new URLSearchParams(location.search).get('ticket');if(!ticket)return;try{const r=await fetch('/api/access/exchange',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ticket})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Acesso expirado');token=d.token;localStorage.setItem('luaImperiosSession',token);history.replaceState({},'',location.pathname)}catch(e){document.querySelector('#loading').textContent=e.message}}
const colors={lua:'#3f9189',bruma:'#a87943',aurora:'#7168a0',ferro:'#944e53'};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{'content-type':'application/json',authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha de rede');return d}
function svg(tag,attrs={}){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
function renderMap(){const map=$('#map');map.replaceChildren();const cols=6,rows=6,w=120,h=78;state.provinces.forEach((p,i)=>{const x=(i%cols)*w+3,y=Math.floor(i/cols)*h+3,jitter=(i%3)*3;const points=`${x+5},${y+8+jitter} ${x+w-10},${y+2} ${x+w-2},${y+h-15} ${x+w-18},${y+h-2} ${x+8},${y+h-7}`;const poly=svg('polygon',{points,class:`province ${p.owner!==state.ownerId?'enemy':''} ${p.capital?'capital':''}`,fill:colors[p.owner]||'#555',tabindex:0});poly.dataset.id=p.id;poly.addEventListener('click',()=>selectProvince(p.id));poly.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectProvince(p.id)}});map.append(poly);const label=svg('text',{x:x+58,y:y+36,class:'map-label'});label.textContent=p.name.split(' ')[0];map.append(label);const troops=svg('text',{x:x+58,y:y+52,class:'troop-label'});troops.textContent=`⚔ ${p.troops}`;map.append(troops)})}
function selectProvince(id){selected=state.provinces.find(p=>p.id===id);$('.game aside').classList.add('open');renderDetails();document.querySelectorAll('.province').forEach(e=>e.classList.toggle('selected',e.dataset.id===id))}
function renderDetails(){const p=selected;if(!p)return;$('#province-name').textContent=p.name;const own=p.owner===state.ownerId;const owner=state.nations.find(n=>n.id===p.owner);$('#province-content').replaceChildren();const facts=document.createElement('div');facts.className='facts';[['Nação',owner?.name],['Terreno',p.terrain],['Tropas',p.troops],['População',p.population],['Recrutáveis',p.recruitable],['Construções',p.buildings.length?p.buildings.join(', '):'Nenhuma']].forEach(([a,b])=>{const d=document.createElement('div');const s=document.createElement('small');s.textContent=a;const strong=document.createElement('b');strong.textContent=b;d.append(s,strong);facts.append(d)});$('#province-content').append(facts);const actions=$('#actions');actions.replaceChildren();if(!own){if(selected&&state.provinces.some(x=>x.id===selected.id)){const source=state.provinces.find(x=>x.owner===state.ownerId&&x.neighbors.includes(p.id));if(source){addAction('Atacar a partir de '+source.name,'attack',()=>battlePrompt(source,p))}}return}addAction('Construir Mercado · 240 ouro','build',()=>doAction({type:'build',provinceId:p.id,building:'market'}),p.buildings.includes('market'));addAction('Construir Quartel · 220 ouro','build',()=>doAction({type:'build',provinceId:p.id,building:'barracks'}),p.buildings.includes('barracks'));addAction('Construir Fortaleza · 300 ouro','build',()=>doAction({type:'build',provinceId:p.id,building:'fortress'}),p.buildings.includes('fortress'));addAction('Recrutar tropas · 8 ouro/unidade','recruit',()=>{const n=prompt('Quantidade de tropas:', '20');if(n)doAction({type:'recruit',provinceId:p.id,amount:Number(n)})},false);const neighbor=state.provinces.find(x=>x.owner===state.ownerId&&p.neighbors.includes(x.id));if(neighbor)addAction('Mover tropas para '+neighbor.name,'move',()=>{const n=prompt('Quantidade de tropas:', '20');if(n)doAction({type:'move',from:p.id,to:neighbor.id,amount:Number(n)})});}
function addAction(label,type,fn,disabled=false){const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.addEventListener('click',fn);$('#actions').append(b)}
function battlePrompt(source,target){const n=prompt(`Tropas de ${source.name} para atacar ${target.name} (disponíveis: ${source.troops-1}):`,'30');if(n)doAction({type:'attack',from:source.id,to:target.id,amount:Number(n)})}
async function doAction(payload){try{state=await api('/api/game/action',{method:'POST',body:JSON.stringify({...payload,version:state.version,operationId:crypto.randomUUID()})});render();toast('Ação confirmada e salva.')}catch(e){toast(e.message);if(e.message.includes('estado'))load()}}
function render(){renderMap();$('#nation-label').textContent=state.nations.find(n=>n.id===state.ownerId)?.name||'Lua';$('#turn').textContent=state.turn;const n=state.nations.find(n=>n.id===state.ownerId);$('#gold').textContent=n.gold;$('#income').textContent=n.income;$('#population').textContent=state.provinces.filter(p=>p.owner===state.ownerId).reduce((s,p)=>s+p.recruitable,0);if(selected)selectProvince(selected.id);renderLog()}
function renderLog(){const box=$('#log');box.replaceChildren();state.log.slice(0,20).forEach(x=>{const d=document.createElement('div');d.className='log-row';const b=document.createElement('b');b.textContent=`T${x.turn}`;d.append(b,document.createTextNode(x.text));box.append(d)})}
async function load(){try{state=await api('/api/game/state');$('#loading').classList.add('hidden');$('#game').classList.remove('hidden');render()}catch(e){$('#loading').textContent='Acesso expirado. Abra um novo link pelo bot.'}}
async function boot(){await exchangeTicket();if(!token){$('#loading').classList.add('hidden');$('#start').classList.remove('hidden');return}load()}
$('[data-new]').addEventListener('click',async()=>{try{state=await api('/api/game/new',{method:'POST',body:JSON.stringify({nation:$('#nation-choice').value})});$('#start').classList.add('hidden');$('#game').classList.remove('hidden');render()}catch(e){toast(e.message)}});$('[data-continue]').addEventListener('click',load);$('[data-end]').addEventListener('click',()=>doAction({type:'endTurn'}));$('[data-log]').addEventListener('click',()=>$('#log-dialog').showModal());$('[data-help]').addEventListener('click',()=>toast('Selecione províncias, construa, recrute e termine o turno.'));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{b.closest('dialog')?.close();$('.game aside').classList.remove('open')}));document.querySelectorAll('[data-zoom]').forEach(b=>b.addEventListener('click',()=>{zoom=Math.max(.8,Math.min(1.4,zoom+(b.dataset.zoom==='+'?.1:-.1)));$('#map').style.transform=`scale(${zoom})`}));$('[data-center]').addEventListener('click',()=>{$('#map').style.transform='scale(1)';zoom=1});boot();
