'use strict';
const Jimp = require('jimp');
const welcome = require('../welcome/profile');
const templates = require('../welcome/templates');
const W = 1280; const H = 720;
const COLORS = { bg: 0x080514ff, panel: 0x160b2ddd, violet: [178,107,255], blue: [91,150,255], green: [91,230,170], red: [255,100,135], gold: [244,205,110], text: 0xffffffff, muted: 0xcbb8e8ff };
function clean(v) { return String(v == null ? '' : v).normalize('NFC').replace(/[\r\n]+/g, ' ').trim(); }
function fit(font, text, max) { let s = clean(text); while (s.length > 1 && Jimp.measureText(font, s) > max) s = s.slice(0, -1); return s.length < clean(text).length ? `${s.slice(0, -1)}…` : s; }
function wrap(font, text, max, maxLines = 2) { const words = clean(text).split(/\s+/); const lines=[]; let line=''; for (const word of words) { const next=line ? `${line} ${word}` : word; if (Jimp.measureText(font,next)<=max) line=next; else { if(line) lines.push(line); line=word; if(lines.length===maxLines-1) break; } } if(line && lines.length<maxLines) lines.push(line); if(words.join(' ') !== lines.join(' ')) lines[maxLines-1] = fit(font, `${lines[maxLines-1] || ''}…`, max); return lines; }
function rect(img,x,y,w,h,color,alpha=255){ for(let yy=y;yy<y+h;yy++) for(let xx=x;xx<x+w;xx++){if(xx<0||yy<0||xx>=W||yy>=H)continue; const i=img.getPixelIndex(xx,yy),d=img.bitmap.data,a=alpha/255;d[i]=d[i]*(1-a)+color[0]*a;d[i+1]=d[i+1]*(1-a)+color[1]*a;d[i+2]=d[i+2]*(1-a)+color[2]*a;d[i+3]=255;} }
function line(img,x,y,w,color){rect(img,x,y,w,2,color,210);}
async function circleAvatar(img, buffer) { let src; try { src=await Jimp.read(buffer); } catch (_) { src=await Jimp.read(await templates.ensureAvatar()); } const s=Math.min(src.bitmap.width,src.bitmap.height); src.crop((src.bitmap.width-s)/2,(src.bitmap.height-s)/2,s,s).resize(250,250).circle(); img.composite(src,105,170); line(img,95,432,270,COLORS.violet); }
async function renderAuditCard(event, visual = {}) { const img=new Jimp(W,H,COLORS.bg); for(let y=0;y<H;y++) rect(img,0,y,W,1,[8+Math.floor(y/40),5,20+Math.floor(y/8)],255); const accent=event.type==='REMOVE'?COLORS.red:event.type==='PROMOTE'?COLORS.gold:event.type==='DEMOTE'?COLORS.blue:event.type==='JOIN'?COLORS.green:COLORS.violet; rect(img,35,32,1210,656,[20,10,43],255); rect(img,35,32,8,656,accent,255); const fTitle=await Jimp.loadFont(Jimp.FONT_SANS_32_WHITE); const fBig=await Jimp.loadFont(Jimp.FONT_SANS_64_WHITE); const f=await Jimp.loadFont(Jimp.FONT_SANS_16_WHITE); const fSmall=await Jimp.loadFont(Jimp.FONT_SANS_16_WHITE); await circleAvatar(img,visual.avatarBuffer || await templates.ensureAvatar()); img.print(fTitle,78,62,'LUA • COMMUNITY DATABASE'); img.print(fBig,430,70, event.type); const title={JOIN:'NOVO MEMBRO',LEAVE:'MEMBRO SAIU',REMOVE:'MEMBRO REMOVIDO',PROMOTE:'PROMOÇÃO ADMINISTRATIVA',DEMOTE:'REBAIXAMENTO ADMINISTRATIVO'}[event.type] || event.type; img.print(fTitle,430,145,fit(fTitle,title,730)); const name=fit(fBig,event.participantName || event.participantJid || 'Membro',730); img.print(fBig,430,205,name); const rows=[['COMUNIDADE',event.communityName || 'não identificada'],['GRUPO',event.groupName || event.groupJid],['AÇÃO',title],['RESPONSÁVEL',event.actorJid || 'não identificado'],['MOTIVO',event.reason || 'não informado'],['MEMBROS',event.memberCount == null ? 'não informado' : String(event.memberCount)]]; let y=305; for(const [label,value] of rows){ img.print(f,430,y,label); const lines=wrap(f,value,710,2); lines.forEach((v,i)=>img.print(f,650,y+i*22,fit(f,v,590))); y+=38+Math.max(0,lines.length-1)*15; } img.print(fSmall,78,650,fit(fSmall,`EVENT ID: ${event.eventId}`,1080)); img.print(fSmall,1030,650,'LUA DATABASE'); return img.getBufferAsync(Jimp.MIME_PNG); }
module.exports={renderAuditCard};
